networks:
  proxy:
    external: true

services:
  previewInfo:
    container_name: sgm
    image: onboarding-sgm:latest
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.89.1.250