networks:
  proxy:
    external: true

services:
  previewInfo:
    container_name: sgmpreview
    image: onboarding-sgm-preview:latest
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.89.1.150